[package]
name = "dach_front"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
actix-files = "0.6"
sailfish = "0.4.0" 
sailfish-macros = "0.4.0"
derive_more = "0.99.5"
actix-session = { version = "0.7.1", features = ["cookie-session"] }
log = "0.4.16"
reqwest = { version = "0.11.10", features = ["json"] }
#actix-extensible-rate-limit = "0.2.1"
futures = "0.3.21"
actix-multipart = "0.4.0-beta.12" 
actix-form-data = "0.6.2"

